<project name="SurveyApplication" default="validate" basedir="." xmlns:sf="antlib:com.salesforce">

    <property file="build.properties"/>
    <property environment="env"/>

   
    <taskdef resource="com/salesforce/antlib.xml" uri="antlib:com.salesforce">
        <classpath>
            <pathelement location="/ant-salesforce.jar" />
        </classpath>
    </taskdef>

    <!-- Shows check only; never actually saves to the server -->
    <target name="validate">
      <sf:deploy username="${sf.username}" password="${sf.password}" serverurl="${sf.serverurl}" maxPoll="${sf.maxPoll}" deployRoot="codepkg" checkOnly="true"/>
    </target>

    <target name="validateWithTestClass">
      <sf:deploy username="${sf.username}" password="${sf.password}" serverurl="${sf.serverurl}" maxPoll="${sf.maxPoll}" deployRoot="codepkg" checkOnly="true" testlevel="RunSpecifiedTests">
        <runTest></runTest>
      </sf:deploy>
    </target>

</project>
